---
aws:
  - 'Amazon Web Services'

database-access:
  - 'Database Access'

github:
  - 'GitHub'

control-panel:
  - 'Control Panel'

jupyterlab:
  - 'JupyterLab'

rstudio:
  - 'RStudio'

migratiion-support:
  - 'Migration Support'
  
moj-cloud-platform:
  - 'MoJ Cloud Platform'

moj-modernisation-platform:
  - 'MoJ Modernisation Platform'

user-account:
  - 'User and Account'
