---
name: Analytical Platform Support Request
description: Request support from the Analytical Platform team
title: "Brief description of your issue"
labels: ["ap-support", "triage"]
assignees:
  - moj-data-platform-robot
body:
  - type: markdown
    attributes:
      value: |
      🔎 Check for a solution in our user guidance here or search GitHub here, or this channel via :slack: search.
      ✨ If you can't find an answer then please log a support issue via our new GitHub Issues template here
      🙋 Please always include your :github: GitHub user name with :slack: slack support message requests
      👋 If you are a new user follow guidance here and email your request to analytical_platform@digital.justice.gov.uk. (We may need one working day to action).
      🚚 If your request is regarding App Migration please use [#data-platform-application-migration-support](https://mojdt.slack.com/archives/C0504KY0Z2N)        
      Thanks for taking the time to fill out this support request form!
  - type: dropdown
    id: tool
    attributes:
      label: Which tool do you need help with?
      multiple: true
      options:
        - GitHub
        - Amazon Web Services
        - Control Panel
        - JupyterLab
        - RStudio
        - Auth0
        - Database Access
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see, but don't include any sensitive information
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
