---
name: Analytical Platform Support Request
description: Request support from the Analytical Platform team
title: "[AP Support]: "
labels: ["ap-support", "triage"]
assignees:
  - "@ministryofjustice/analytical-platform-support"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request form!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
