---
name: Analytical Platform Support Request
description: Request support from the Analytical Platform team
title: "Brief description of your issue"
labels: ["ap-support", "triage"]
assignees:
  - moj-data-platform-robot
body:
  - type: markdown
    attributes:
      value: |
        🔎 Check for a solution in our user guidance [here](https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html), search GitHub [here](https://github.com/ministryofjustice/data-platform-support/issues?q=is%3Aissue), or the support channel [here](https://mojdt.slack.com/archives/C4PF7QAJZ)
        Thanks for taking the time to fill out this support request form!
  - type: dropdown
    id: tool
    attributes:
      label: Which tool do you need help with?
      multiple: true
      options:
        - Amazon Web Services
        - Application Migration Support
        - Auth0
        - Control Panel
        - Database Access
        - JupyterLab
        - RStudio
        - S3
        - User and Account
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see, but don't include any sensitive information
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
