---
name: Redeploy App Request
description: Request to redeploy your app to the Analytical Platform team
title: "Change to Name of App"
labels: ["ap-support", "redeploy"]
assignees:
  - moj-data-platform-robot
  - EO510
  - YvanMOJdigital
body:
  - type: markdown
    attributes:
      value: |
        Please complete this form below, the team will be working on a schedule of issue requests submitted by COP (5:30pm) Friday for deployment the following week (currently scheduled for Wednesdays).
  - type: dropdown
    id: repo
    attributes:
      label: App Repository Access
      description: If it must remain private, please leave contact details for a repo admin (Slack/email) here so that an AP team member can arrange access ahead of the redeployment
      multiple: false
      options:
        - Public
        - Internal
        - Private
  - type: textarea
    id: app-version
    attributes:
      label: What is the new version number for the app?
    validations:
      required: true
  - type: textarea
    id: date-requested
    attributes:
      label: Is the update needed for a specific date?
      placeholder: If yes then enter date and explain impact if it is not updated by this date
  - type: textarea
    id: impact-delivery
    attributes:
      label: What's the impact on delivery if it is not updated by this date?
  - type: textarea
    id: update-involvement
    attributes:
      label: What's involved in the update?
  - type: textarea
    id: why-critical
    attributes:
      label: Why is this critical? A high level description please
  - type: textarea
    id: impact
    attributes:
      label: How many users will this impact?
  - type: dropdown
    id: security
    attributes:
      label: Is this a security fix?
      multiple: false
      options:
        - "Yes"
        - "No"
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency to another project/policy/activity?
      multiple: false
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: dependency-text
    attributes:
      label: If yes to the above what is the link?
  - type: dropdown
    id: commercial
    attributes:
      label: Is there any commercial impact?
      multiple: false
      options:
        - "Yes"
        - "No"
  - type: dropdown
    id: refresh-data
    attributes:
      label: Is this update to refresh data?
      multiple: false
      options:
        - "Yes"
        - "No"
