---
name: Data Platform Support Request
description: Request support from the Data Platform team
title: "Brief description of your issue"
labels: ["dp-support", "triage"]
assignees:
  - moj-data-platform-robot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request form!
  - type: dropdown
    id: tool
    attributes:
      label: Which tool do you need help with?
      multiple: true
      options:
        - GitHub
        - Amazon Web Services
        - MoJ Cloud Platform
        - MoJ Modernisation Platform
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see, but don't include any sensitive information
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
