---
name: Issue staler

on:
  schedule:
    - cron: "30 1 * * *"

permissions: read-all

jobs:
  issue-stale:
    name: Issue staler
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Issue staler
        id: issue_staler
        uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
