---
name: Issue labeler

on:
  issues:
    types:
      - opened
      - edited

permissions: read-all

jobs:
  issue-labeler:
    name: Issue labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Issue labeler
        id: issue_labeler
        uses: github/issue-labeler@98b5412841f6c4b0b3d9c29d53c13fad16bd7de2 # v3.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          sync-labels: true
