---
name: Issue labeler

on:
  issues:
    types:
      - opened
      - edited

permissions: read-all

jobs:
  issue-labeler:
    name: Issue labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: issue labeler
        id: issue_labeler
        uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true